id: PE3B664B2
initial_creation_type: input
source_metadata:
  title: Songs and Poems Series
  language: bo
  description: 'A selection of spiritual songs (mgur; glu) or poems:'
  volume:
    3427de63e2c54f8199e3b4246148e92b:
      title: Acrostic Song
      parent: Acrostic
    4afc501f906944b387e2b660528e294d:
      title: A Song for Travelling from Sikkim to Tibet
      parent: Advice
    ff44d3dc717d4cba918044a0b87b2f78:
      title: Advice to Myself Exposing Hidden Flaws
      parent: Advice
    bfe78d1e31a8443eb6bba7a7c764e69a:
      title: Khandro's Plea
      parent: Advice
    31ee6089580d44dc8178aa8ca62868e8:
      title: 'The Blissful Path to Awakening: A Song on the Essence of Definitive
        Meaning'
      parent: Advice
    b9d01478133644edbe62057f9a719bbe:
      title: How to Take the Practice to Heart
      parent: Advice
    f0c62164739e41f89dec909b01e1b6e2:
      title: 'The Sound of the Divine Drum: Advice at a Time of Victory'
      parent: Advice
    a7069efc879643979e5462186c2dfe59:
      title: Many Are the Scholars Who Travel Empty-Handed to the Realm of the Dead
      parent: Advice
    12f5f0645ac74584a4d572b13fdd9da9:
      title: 'Divine Music: Words of Encouragement for the Authentic Path'
      parent: Advice
    505f897ddedb4dbab76ffb76f50613ec:
      title: Song of the Enchanting Wildwoods
      parent: Advice
    faf23d5b0dfc4caf81c55b98da56cb69:
      title: A Song of Amazement Inspired by Practice Experience
      parent: Advice
    f1c682665a34440993cc53f5cc9ea132:
      title: 'Rain of Accomplishments: A Song that Incorporates the Four Mindfulnesses
        from an Instruction on the View of the Middle Way'
      parent: Advice
    f0b7b2667da7467baf668772645d3343:
      title: Types of Spiritual Song
      parent: Classification
    0aca686b93af450eabd46352172743c8:
      title: On Jetsün Drakpa Gyaltsen’s How to Take the Practice to Heart
      parent: Commentaries
    6531a1f2866d483cb5d2e5529124c570:
      title: A Song to Aid the Recollection of Parental Kindness and Encourage the
        Recitation of the Maṇi Mantra
      parent: Compassion
    c5aaea5bb8d84ec98dcf7baf78ccd270:
      title: A Song of Compassion
      parent: Compassion
    a978ef8a602842cdbf7d1071540fdee1:
      title: When Remembering My Mother
      parent: Compassion
    63e8cf6b7ea34f31ba773117349bb050:
      title: A Lamenting Plea for Compassion
      parent: Devotion
    1cf7d1f4043746baba2b51c638b58a39:
      title: A Song Recalling the Noble Guru’s Kindness
      parent: Devotion
    c26c89813443411dbb9d5d2bde60cc90:
      title: A Song Requested by the Buddhist Monk Jamyang Yönten Gyatso
      parent: Devotion
    a68bf9089f074f5aa82634365e771a01:
      title: Lament Composed in a State of Deep Sadness
      parent: Devotion
    a2c8fcdfbfa04c09bc0a21f8845823d9:
      title: 'Lightning Bands of Compassion: A Song of Lament for Khenchen Kunzang
        Palden Tupten Chökyi Drakpa'
      parent: Devotion
    0dadd23869c34d278a922e7f5360bff9:
      title: 'Piercing Devotion: A Lament for Lama Sakyapa'
      parent: Devotion
    67642537c5c54de78b4deb25eb68027d:
      title: 'Tremendous Piercing of the Heart: A Lament Recalling the Guru'
      parent: Devotion
    798944ff224d4390b651c0253e8d45da:
      title: 'The Spontaneous Sound of Uncontrived Song: A Lament Recalling the Great
        Guru of Oḍḍiyāna'
      parent: Devotion
    e52ebb6a4687470caf77b59a22b3c955:
      title: The Song of the Vajra
      parent: Dzogchen
    712d41bcc80c47b5a5715fdc61ee613d:
      title: A Song in Six Verses
      parent: Dzogchen
    8ed89774ff0d401ea86144a667b303c2:
      title: Song of Experiential Certainty
      parent: Dzogchen
    2ae4b3d63286416e942064a64ed7a754:
      title: Song that Arose Spontaneously at Taktse Podrang, Sikkim
      parent: Dzogchen
    dadc1d8fa8134993af77121d98e0d01e:
      title: Spontaneously Written Song of Experience
      parent: Dzogchen
    604b2573db774c76ba2a761090bf971d:
      title: A Song of Advice for Gok Zangden
      parent: Dzogchen
    3b0433f650d44bb08a623c2adab788d7:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Dzogchen
    b3db322d37c44716838196dd5eac3fc1:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Dzogchen
    32797db90a194bfab3d7dae516e1c607:
      title: In This Pure Awareness
      parent: Dzogchen
    c5921c2ddba8479c8042e4f1011a7cd1:
      title: 'Aho Ye: Impressions of an Insightful Experience'
      parent: Dzogchen
    662dcbf8c6df48e8871d3f94198ac45b:
      title: Five-Verse Doha of Yogic Realization
      parent: Dzogchen
    6c11bc82f0544bbe9fc3a339849e836f:
      title: 'Mindfulness: The Mirror of the Mind'
      parent: Dzogchen
    9ea163c08712416181bc20f6b351245a:
      title: Natural Great Peace
      parent: Dzogchen
    6ec89cc1020348fab19927daf10e2ffa:
      title: 'Ḍākinī’s Delight: A Song of the Feast'
      parent: Feast Songs
    5e722654259749cf9e908686d378f647:
      title: Song of the Feast (Tsok Lu)
      parent: Feast Songs
    4db56bc762004d478eb666d55f3e870a:
      title: Upon Hearing the Fluted Speech of Kunzang Dechen Tsomo, Queen Mother
        of Sikkim
      parent: General
    4724e1df5f1842afbdaad1ea2c7b3c2c:
      title: 'Nectar of the Heart: An Experiential Song of Parting from the Four Attachments'
      parent: General
    ee4402b2ad58410398549024d7bf4533:
      title: A Short Song of Practice
      parent: General
    b668c72fa184423498e49c054dcc5672:
      title: When Flowers Were Ravaged by the Frost
      parent: Impermanence
    d7349d573a8545049c47bd7c5f32d326:
      title: Verses of Advice for Meditating on Impermanence
      parent: Impermanence
    d88062a5fe7d46609fc4dd9f8c96b392:
      title: 'A Yogi’s Song of Happiness: The Melody that Brings Universal Auspiciousness
        and Fulfilment'
      parent: Joy
    608673b4bc75446fa71bc58f86487972:
      title: Drawing Out the Quintessence of the View
      parent: Lamdré
    d7d2ca61a1614ab58e00b8c39bba6e31:
      title: Song of Deathlessness
      parent: Longevity
    06194699a57b4f089ff916a2815de07a:
      title: 'The Excellent Path of Definitive Meaning: An Unmistaken Expression of
        the Definitive Mahāmudrā'
      parent: Mahāmudrā
    cfe36a3c20e84b46a0de5f855fb34a3e:
      title: 'Lightning Band of Faith: A Song to Invoke the Master’s Wisdom Mind'
      parent: Prayer
    48065eddc6424ea582c7d631752a8fe7:
      title: A Song of Prayer to Jamyang Loter Wangpo
      parent: Prayer
    76041880c0314ee8b0728a61eed93b7a:
      title: 'Auspicious Dance of Longevity: A Song for Touring the Sacred Sites of
        Nepal'
      parent: Sacred Places
    a9bcf83394d048dab69492d8cf72a677:
      title: Upon Arriving at Yangleshö
      parent: Sacred Places
    c09a9b6d87784e3dbc0e40f00e4cc129:
      title: Jangphen Namkha Dzong
      parent: Sacred Places
    feb6e669135645858e9ce598bce6f9fb:
      title: 'Great Stake to the Heart: A Song of Sadness'
      parent: Sadness
    b95f3d097bc844c28d76b37beb998056:
      title: Song of Prayer to Milarepa
      parent: Sadness
    439c3127ad3a4c548dde1417bd19f028:
      title: Twelve and a Half Crippled Verses
      parent: Wonder
created_at: '2022-03-01T05:55:44.209497'
last_modified_at: '2022-03-01T05:55:44.209500'
